In [2]:
# Python program for random 
# binary string generation 
import numpy as np
import random 
  


# Function to create random binary string of length p
def rand_key(p): 
    
    # Variable to store in an array 
    key = []
  
    # Loop to find the string 
    # of desired length 
    for i in range(p): 
          
        # randint function to generate 
        # 0, 1 randomly and add  
        # the result into arry
        key.append(random.randint(0, 1)) 
    return(key) 


# Excercise 1


# Question 1


In [3]:

#test case
x = np.array([1,0,1,1,1]) #password
c1 = np.array([0,1,0,1,1]) #challenge vector c1
c2 = np.array([1,1,1,1,0]) #challenge vector c1

b1 = np.dot(x,c1) % 2 # b = c dot product x
b2 = np.dot(x,c2) % 2 # b = c dot product x

In [4]:
#challenge 1

print("Answer for challenge vector c1 is {}".format(b1))
print("Answer for challenge vector c2 is {}".format(b2))

Answer for challenge vector c1 is 0
Answer for challenge vector c2 is 1


# Question 2
# (01011 + 11110) ⋅ x = 01011 ⋅ x + 11110 ⋅ x
# find the challnge bit that solve this 

In [5]:
respond = (b1 + b2) % 2
respond #respoond to #(01011 + 11110) ⋅ x = 01011 ⋅ x + 11110 ⋅ x
print("Respond to the new challnge vectors is {}".format(respond))

Respond to the new challnge vectors is 1


# Question 3:
Extending the above idea, Eve can compute the right response to the sum of any number of
previous challenges for which she has the right response. Mathematically,
if 
c1 ⋅ x = 𝛽1, c2 ⋅ x = 𝛽2, ⋯ , c𝑘 ⋅ x = 𝛽1, 𝑡ℎ𝑒𝑛 (c1 + c2 + ⋯ + c𝑘) ⋅ x = (𝛽1+𝛽2+⋯+𝛽𝑘)
Assume Eve knows the following challenges and responses:
# Challenge Response
# 110011       0
# 101010       0
# 111011       1
# 001100       1

In [15]:
ch = np.array([[1,1,0,0,1,1],[1,0,1,0,1,0],[1,1,1,0,1,1],[0,0,1,1,0,0]]) #challenges Eve knows
re = np.array([0,0,1,1]) #Eve respond to the challenge respectivly 
c_a = np.array([0,1,1,0,0,1])
c_b = np.array([1,1,0,1,1,1])


In [16]:
'''Function takes in ch (array of challenge) and add them together mod the bits
#and comapir if equal to challenge Ca or Cb 
#using c1 ⋅ x = 𝛽1, c2 ⋅ x = 𝛽2, ⋯ , c𝑘 ⋅ x = 𝛽1, 𝑡ℎ𝑒𝑛 (c1 + c2 + ⋯ + c𝑘) ⋅ x = (𝛽1+𝛽2+⋯+𝛽𝑘)
# response arguments takes in the respond corresponding to the challenge in ch
logic

numpy.all(a, axis=None, out=None, keepdims=<no value>)[source]
Test whether all array elements along a given axis evaluate to True.

'''
def generate_re(c):
    for i,v1 in enumerate(ch):
        for j,v2 in enumerate(ch):
            vsum = np.mod(v1+v2,2)
            #print(vsum)
            if(vsum == c).all():
                return (re[i] + re[j]) % 2



In [18]:
re_a  = generate_re(c_1) #respond for c_a 
re_b = generate_re(c_2) #respond for c_b

In [21]:
print("Respond for c_a = 011001 is",re_a)
print("Respond for c_a = 110111 is",re_b)

Respond for c_a = 011001 is 0
Respond for c_a = 110111 is 0


# Question 4:


In [22]:
challenges = np.array([[1,1,0,0,1,1],[1,0,1,0,1,0],[1,1,1,0,1,1],[0,0,1,1,0,0],[0,1,1,0,1,1],[1,1,0,1,0,0]])
 #store the challenges in to a  6 x 6 matrix
print(challenges)
print(challenges.shape)

[[1 1 0 0 1 1]
 [1 0 1 0 1 0]
 [1 1 1 0 1 1]
 [0 0 1 1 0 0]
 [0 1 1 0 1 1]
 [1 1 0 1 0 0]]
(6, 6)


In [23]:
responses = np.array([0,0,1,1,0,1])
print(responses) #store the individual responses in to a vector correspondind to the challenges element
print(responses.shape)
b = sum(responses) % 2 #reponses sume mod 2

[0 0 1 1 0 1]
(6,)


In [24]:
from scipy import linalg
x = linalg.solve(challenges,responses)
for i,num in enumerate(x):
        x[i] = x[i] % 2 #mod each element by 2
print("The password is ",x)

The password is  [1. 0. 1. 0. 0. 1.]
