In [395]:
import numpy as np
from math import sqrt

In [396]:
A = np.array([
    [-6,-3,6,1],
    [-1,2,1,-6],
    [3,6,3,-2],
    [6,-3,6,-1],
    [2,-1,2,3],
    [-3,6,3,2],
    [-2,-1,2,-3],
    [1,2,1,6]
             ])
A

array([[-6, -3,  6,  1],
       [-1,  2,  1, -6],
       [ 3,  6,  3, -2],
       [ 6, -3,  6, -1],
       [ 2, -1,  2,  3],
       [-3,  6,  3,  2],
       [-2, -1,  2, -3],
       [ 1,  2,  1,  6]])

In [397]:
len(A[:,0])
len(A[0])

4

The number of rows of a list of lists would be: len(A) and the number of columns len(A[0]) given that all rows have the same number of columns, i.e. all lists in each index are of the same size.

# Q1a

In [398]:
def orthoganal(A):
    fail = []
    m = len(A[:,0])
    n = len(A[0])
    for i in range(0,n):
       #print(A[:,i])
        trans = np.zeros([1,m])
        for j in range(0,m): #tanspose the current matrix before compair to the rest
            trans[0][j] = A[j][i]
        #print(trans)
        for x in range (i + 1,n):
            total = 0
            #print(A[:,x])
            print("Coulum A{} dot Column A{}".format(i,x))
            for y in range(0,m):
                total = total + (A[y][x] * trans[0][y])
            print("The dot product is",total)
            if(total == 0):
                print("Coulum A{} dot Column A{} is orthogonal".format(i,x))
            else:
                print("Coulum A{} dot Column A{} is not orthogonal".format(i,x))
            print("\n")

In [417]:
def orthoganal(A):
    fail = []
    m = len(A[:,0])
    n = len(A[0])
    for i in range(0,n):
        for x in range (i + 1,n):
            total = 0
            
            #print(A[:,x])
            print("Coulum A{} dot Column A{}".format(i,x))
            print("The dot product may not be exactly 0 but very small or close to zero due to floating point conversion")
            
            for row in range(0,m):
                total = total + (A[:,i][row] * A[:,x][row])
                
            if(total < 1.0e-14 ):
                print("The dot product is",0)
            else:
                print("The dot product is",total)
            
            if(total < 1.0e-12):  #safer as computer aproximate so if num is very small but not zero it wont make this estimate error
                print("Coulum A{} dot Column A{} is orthogonal".format(i,x))
            else:
                print("Coulum A{} dot Column A{} is not orthogonal".format(i,x))
            print("\n")

# Q1b

In [418]:
orthoganal(A)

Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A0 dot Column A3
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A3 is orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A2 is orthogonal


Coulum A1 dot Column A3
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A3 is orthogonal


Coulum A2 dot Column A3
The dot product may not be exactly 0 but 

# Q1c
### Definition. We say that 2 vectors are orthogonal if they are perpendicular to each other. i.e. the dot product of the two vectors is zero.
### Definition. We say that a set of vectors {v1, v2, ..., vn} are mutually orthogonal if every pair of vectors is orthogonal. i.e. vi dot vj = 0, for all i != j

# Q2. Write a module “Orthonormalisation” that defines a a procedure orthonormalise(L) with the following specs:

In [419]:
A2 = np.array([
    [4,3,1,2],
    [8,9,-5,-5],
    [10,1,-1,5]
])
orthoganal(A2)

Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 94
Coulum A0 dot Column A1 is not orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A0 dot Column A3
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 18
Coulum A0 dot Column A3 is not orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A2 is orthogonal


Coulum A1 dot Column A3
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A3 is orthogonal


Coulum A2 dot Column A3
The dot product may not be exac

In [420]:
A2 = np.array([
    [4,8,10],
    [3,9,1,],
    [1,-5,-1],
    [2,-5,5]
])
orthoganal(A2)

Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 44
Coulum A0 dot Column A1 is not orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 52
Coulum A0 dot Column A2 is not orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 69
Coulum A1 dot Column A2 is not orthogonal




In [421]:
def gs(A): # gram schmidth process 
    # A IS  M X N MATRIX AND HAVE TI BE LINEARLY INDEPENDENT COLUMNS
    m = len(A[:,0])
    n = len(A[0])
    #print(m)
    ortho = np.zeros([m,n]) # orthogonal matrix
    for i in range(0,n):
        if(i == 0):
            ortho[:,i] = A[:,i] # set x1 to v1
            continue
        x = A[:,i]
        for j in range(0,i):
            total = 0
            length = 0
            
            for row in range(m): # x.v
                total = total + (x[row] * ortho[:,j][row])
                
            for row in range(m): # v.v
                length = length + (ortho[:,j][row] * ortho[:,j][row])
                
            scaler = total / (length)

            x = x - (scaler * ortho[:,j])
        ortho[:,i] = x
    print("Before normalising")
    print(ortho)
    # NORMALIZATION PROCESS 
    for col in range(n):
        total = 0
        for row in range(m):
            total = total + (ortho[:,col][row] * ortho[:,col][row] ) # ||v||^2
        norm = 1/ sqrt(total) #||v||
        
        ortho[:,col] = norm * ortho[:,col]
     
    print("After performing Gram schmidt on the matrix and normalising")
    print("Produce a orthogonal matrix, with orthonormal columns (unit length 1)")
    print(ortho)
    orthoganal(ortho)


In [422]:
gs(A2)

Before normalising
[[ 4.          2.13333333  3.18548799]
 [ 3.          4.6        -3.94379152]
 [ 1.         -6.46666667 -3.09351048]
 [ 2.         -7.93333333  1.09146653]]
After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[ 0.73029674  0.18677078  0.5275409 ]
 [ 0.54772256  0.4027245  -0.6531217 ]
 [ 0.18257419 -0.56614893 -0.51230873]
 [ 0.36514837 -0.69455384  0.18075511]]
Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Co

In [423]:
A3 = np.array([
    [1,2,4],
    [0,0,5],
    [0,3,6],
])
 

In [424]:
A4 = np.array([
    [2,3],
    [2,4],
    [1,1],
])
len(A4[:,0])

3

In [425]:
A5 = np.array([
    [12,-51,4],
    [6,167,-68],
    [-4,24,-41],

])
gs(A5)
    

Before normalising
[[ 12.  -69.  -11.6]
 [  6.  158.    1.2]
 [ -4.   30.  -33. ]]
After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A2 is orthogonal




In [426]:
gs(A3)

Before normalising
[[1. 0. 0.]
 [0. 0. 5.]
 [0. 3. 0.]]
After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A2 is orthogonal




In [427]:
gs(A4)

Before normalising
[[ 2.         -0.33333333]
 [ 2.          0.66666667]
 [ 1.         -0.66666667]]
After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[ 0.66666667 -0.33333333]
 [ 0.66666667  0.66666667]
 [ 0.33333333 -0.66666667]]
Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal




## Q3a. Write a program to compute the QR factorization of matrix A = QR, where Q is orthonormal and R is upper triangular. (refer to lecture notes for the theory). You may assume A consists of linearly independent vectors.

### A = QR
### (Q^T)(A) = (Q^T)(Q)(R) = R
### R = (Q^T)(R)
#### (Q^T)(Q) = Identity I matrix if Q have orthonormal columns
#### R is an upper trianger matrix

In [428]:
A4 = np.array([
    [2,3],
    [2,4],
    [1,1],
])


In [443]:
def gs(A): # gram schmidth process 
    # A IS  M X N MATRIX AND HAVE TI BE LINEARLY INDEPENDENT COLUMNS
    m = len(A[:,0])
    n = len(A[0])
    #print(m)
    ortho = np.zeros([m,n]) # orthogonal matrix
    for i in range(0,n):
        if(i == 0):
            ortho[:,i] = A[:,i] # set x1 to v1
            continue
        x = A[:,i]
        for j in range(0,i):
            total = 0
            length = 0
            
            for row in range(m): # x.v
                total = total + (x[row] * ortho[:,j][row])
                
            for row in range(m): # v.v
                length = length + (ortho[:,j][row] * ortho[:,j][row])
                
            scaler = total / (length)

            x = x - (scaler * ortho[:,j])
        ortho[:,i] = x
    print("Before normalising")
    print(ortho)
    print("\n")
    # NORMALIZATION PROCESS 
    for col in range(n):
        total = 0
        for row in range(m):
            total = total + (ortho[:,col][row] * ortho[:,col][row] ) # ||v||^2
        norm = 1/ sqrt(total) #||v||
        
        ortho[:,col] = norm * ortho[:,col]
     
    print("After performing Gram schmidt on the matrix and normalising")
    print("Produce a orthogonal matrix, with orthonormal columns (unit length 1)")
    print(ortho)
    print("\n")
    
    orthoganal(ortho)
    
    return ortho # Q

In [444]:
Q = gs(A4)

Before normalising
[[ 2.         -0.33333333]
 [ 2.          0.66666667]
 [ 1.         -0.66666667]]


After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[ 0.66666667 -0.33333333]
 [ 0.66666667  0.66666667]
 [ 0.33333333 -0.66666667]]


Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal




In [445]:
def QR_decomposition(Q,A):
    #(Q^T)(A) = (Q^T)(Q)(R) = R
    
    #tranpose Q
    m = len(Q[:,0])
    n = len(Q[0])
    Q_trans = np.zeros([n,m]) 
    
    # iterate through rows
    for i in range(m):
   # iterate through columns
       for j in range(n):
        Q_trans[j][i] = Q[i][j]
    #print(Q_trans)
    R = np.zeros([n,n])
    
    #(Q^T)(A)
    for i in range(len(Q_trans)):
        for j in range(len(A[0])):
            for k in range(len(A)):
                R[i][j] = R[i][j] + (Q_trans[i][k] * A[k][j])
                
            if(R[i][j] < 1.0e-12): # due to computer arithmatic very small number floating point error round 
                R[i][j] = 0 #set very very small number to 0 due to floating round up error during arithmatic
                    
    print(R)

In [446]:
QR_decomposition(Q,A4)

[[3. 5.]
 [0. 1.]]


In [447]:
Q = gs(A3)


Before normalising
[[1. 0. 0.]
 [0. 0. 5.]
 [0. 3. 0.]]


After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal


Coulum A0 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A2 is orthogonal


Coulum A1 dot Column A2
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A1 dot Column A2 is orthogonal




In [448]:
QR_decomposition(Q,A3)

[[1. 2. 4.]
 [0. 3. 6.]
 [0. 0. 5.]]


In [452]:
A5 = np.array([
    [2,1],
    [2,1],
    [1,5]
])


In [453]:
Q = gs(A5)

Before normalising
[[ 2. -1.]
 [ 2. -1.]
 [ 1.  4.]]


After performing Gram schmidt on the matrix and normalising
Produce a orthogonal matrix, with orthonormal columns (unit length 1)
[[ 0.66666667 -0.23570226]
 [ 0.66666667 -0.23570226]
 [ 0.33333333  0.94280904]]


Coulum A0 dot Column A1
The dot product may not be exactly 0 but very small or close to zero due to floating point conversion
The dot product is 0
Coulum A0 dot Column A1 is orthogonal




In [454]:
QR_decomposition(Q,A5)

[[3.         3.        ]
 [0.         4.24264069]]
