In [6]:
# Transform a matrix to reduced row echelon form
 
import numpy as np

'''Function to transform a matrix to reduced row echelon form'''
def rref(A):
    tol = 1e-16
    #A = B.copy()
    rows, cols = A.shape
    r = 0
    pivots_pos = []
    row_exchanges = np.arange(rows)
    for c in range(cols):
        ## Find the pivot row:
        pivot = np.argmax (np.abs (A[r:rows,c])) + r
        m = np.abs(A[pivot, c])
        if m <= tol:
        ## Skip column c, making sure the approximately zero terms are
        ## actually zero.
            A[r:rows, c] = np.zeros(rows-r)
        else:
            ## keep track of bound variables
            pivots_pos.append((r,c))

            if pivot != r:
                ## Swap current row and pivot row
                A[[pivot, r], c:cols] = A[[r, pivot], c:cols]
                row_exchanges[[pivot,r]] = row_exchanges[[r,pivot]]

            ## Normalize pivot row
            A[r, c:cols] = A[r, c:cols] / A[r, c];

            ## Eliminate the current column
            v = A[r, c:cols]
            ## Above (before row r):
            if r > 0:
                ridx_above = np.arange(r)
                A[ridx_above, c:cols] = A[ridx_above, c:cols] - np.outer(v, A[ridx_above, c]).T
                ## Below (after row r):
            if r < rows-1:
                ridx_below = np.arange(r+1,rows)
                A[ridx_below, c:cols] = A[ridx_below, c:cols] - np.outer(v, A[ridx_below, c]).T
                r += 1
        ## Check if done
        if r == rows:
            break;
    return A


In [16]:
# A,B,C,D friend matrix
F = np.array([[0,1,1,1],
              [1,0,1,0],
              [1,1,0,1],
              [0,1,1,0]])

#Linking matrix
L = np.array([[0,1/3,1/3,1/2],
              [1/2,0,1/3,0],
              [1/2,1/3,0,1/2],
              [0,1/3,1/3,0]])

print("freind matrix\n",F)
print('\n')
print("Linking matrix\n",L)


freind matrix
 [[0 1 1 1]
 [1 0 1 0]
 [1 1 0 1]
 [0 1 1 0]]


Linking matrix
 [[0.         0.33333333 0.33333333 0.5       ]
 [0.5        0.         0.33333333 0.        ]
 [0.5        0.33333333 0.         0.5       ]
 [0.         0.33333333 0.33333333 0.        ]]


In [17]:
# 4x4 Identity transformation matrix
I = np.eye(4) #float
print(I)

#L - I
A = (L - I)*6 #make matrix to whole number for eaiser to row reduce
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-6.  2.  2.  3.]
 [ 3. -6.  2.  0.]
 [ 3.  2. -6.  3.]
 [ 0.  2.  2. -6.]]


In [9]:
AguA = np.array([[-1.,1/3,1/3,0.5,0.],
                [ 0.5, -1.  ,1/3  ,0.,0.],
                [ 0.5,1/3 ,-1.,0.5,0.],
                [ 0.,1/3  ,1/3 ,-1. ,0.]])
AguA = AguA * 6
AguA

array([[-6.,  2.,  2.,  3.,  0.],
       [ 3., -6.,  2.,  0.,  0.],
       [ 3.,  2., -6.,  3.,  0.],
       [ 0.,  2.,  2., -6.,  0.]])

In [10]:
rref((L-I)*6)

array([[ 1.    ,  0.    ,  0.    , -1.5   ],
       [ 0.    ,  1.    ,  0.    , -1.3125],
       [ 0.    ,  0.    ,  1.    , -1.6875],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

In [19]:
echelon_A = rref(AguA)
echelon_A

array([[ 1.    ,  0.    ,  0.    , -1.5   , -0.    ],
       [ 0.    ,  1.    ,  0.    , -1.3125,  0.    ],
       [ 0.    ,  0.    ,  1.    , -1.6875,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

In [24]:
print("poplarity vector ")
print("rA: ",abs(echelon_A[0][3]))
print("rB: ",abs(echelon_A[1][3]))
print("rC: ",abs(echelon_A[2][3]))
print("rD: free variable")

poplarity vector 
rA:  1.5
rB:  1.3125
rC:  1.6875
rD: free variable


# Question 4:
# (a) Does the equation Lr = r above always have a solution?
## Yes Lr = r always have a solution as only 3 pivot columns thus 1 free variable therefore infinitly many solutions
# (b) Will a solution have entries that are nonnegative?
# Yes since have 1 free variable it could be any number thus the infinite solution therefore could have a entries that are negative.
# (c) Is the solution unique? If not, we will have conflicting rankings.
# Solution not unique as have free variable.It is possible to have conflicting ranking as we have infinite solutions

# Question 5


In [52]:
#Question 5
F = np.array([[0,1,1,1,1],
            [1,0,1,0,0],
            [1,1,0,0,1],
            [1,0,1,0,1],
             [0,0,1,0,0]])

L = np.array([[0,1/2,1/4,1,1/3],
            [1/3,0,1/4,0,0],
            [1/3,1/2,0,0,1/3],
            [1/3,0,1/4,0,1/3],
             [0,0,1/4,0,0]])

# 5x5 Identity transformation matrix
I = np.eye(5) #float
print("Identity matrix\n\n",I)

#L - I
A = (L - I) * 12  #to get whole number thus easier to compute
print("\nMatrix A:\n",A)

print("\nLinking matrix\n",L)

print("\n L - I")
print(L-I)
#Agumented matrix
# [A |0]

AguA = np.array([[-12,6,3,12,4,0],
                [4,-12,3,0,0,0],
                [4,6,-12,0,4,0],
                [4,0,3,-12,4,0],
                [0,0,3,0,-12,0]])

AguA = AguA.astype(float)
print("\n Agumented martrix\n",AguA)

reduce_A = rref(AguA)
print("\nReduce echolon form of AguA\n",reduce_A)


print("rA: ",abs(reduce_A[0][4]))
print("rB: ",abs(reduce_A[1][4]))
print("rC: ",abs(reduce_A[2][4]))
print("rD: ",abs(reduce_A[3][4]))
print("rE: free variable")

Identity matrix

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matrix A:
 [[-12.   6.   3.  12.   4.]
 [  4. -12.   3.   0.   0.]
 [  4.   6. -12.   0.   4.]
 [  4.   0.   3. -12.   4.]
 [  0.   0.   3.   0. -12.]]

Linking matrix
 [[0.         0.5        0.25       1.         0.33333333]
 [0.33333333 0.         0.25       0.         0.        ]
 [0.33333333 0.5        0.         0.         0.33333333]
 [0.33333333 0.         0.25       0.         0.33333333]
 [0.         0.         0.25       0.         0.        ]]

 L - I
[[-1.          0.5         0.25        1.          0.33333333]
 [ 0.33333333 -1.          0.25        0.          0.        ]
 [ 0.33333333  0.5        -1.          0.          0.33333333]
 [ 0.33333333  0.          0.25       -1.          0.33333333]
 [ 0.          0.          0.25        0.         -1.        ]]

 Agumented martrix
 [[-12.   6.   3.  12.   4.   0.]
 [  4. -12.   3.   0.   0.   0.]
 [  4.   6. -12.   