In [108]:
import numpy as np

# Q1. Write a code to find ech form (over binary matrices), i.e. entries of matrices are always 0,1 even in reduction stage.
##  Gaussian Elimination

In [109]:
row = input("Enter the row size of the agumented matrix: ")
col = input("Enter the column size of the agumented matrix: ")
row = int(row)
col = int(col)

Enter the row size of the agumented matrix: 3
Enter the column size of the agumented matrix: 4


In [110]:
agu = np.zeros((row,col),float)
for i in range(row):
    for j in range(col):
        agu[i][j] = input("Enter a[{0}][{1}]:".format(i,j))
        

Enter a[0][0]:1
Enter a[0][1]:1
Enter a[0][2]:-1
Enter a[0][3]:9
Enter a[1][0]:0
Enter a[1][1]:1
Enter a[1][2]:3
Enter a[1][3]:3
Enter a[2][0]:-1
Enter a[2][1]:0
Enter a[2][2]:-2
Enter a[2][3]:2


In [111]:
agu


array([[ 1.,  1., -1.,  9.],
       [ 0.,  1.,  3.,  3.],
       [-1.,  0., -2.,  2.]])

In [112]:
#able to handle agumented matrix A
# Elimination

def ref(agu):


    n = len(agu) # same as how many rows
    print("row size is",n)

    for k in range(n-1):
        for i in range(k+1,n): 
            if agu[i,k] == 0:
                continue
            factor = agu[k,k] / agu[i,k]
            for j in range(k,n+1): #row operation step to get pivot colmuns
                agu[i,j] = agu[k,j] - agu[i,j] * factor # r one row is subtracted by a another row ERO
            

    #back substitution part
    # since after gaussian elimination if consistent x[n-1] the last entry of the solution will have a solution
    # back substitute upwards
    x = np.zeros(n,float)
    x[n-1] = agu[n-1,n] / agu[n-1,n-1] 

    print(x)
    # n-2 is the row just before last one, -1 as we want to stop after doing index 0 due to range,-1 to go backward
    for i in range(n-2,-1,-1):
        sum_ax = 0
        for j in range(i+1,n):
            sum_ax = sum_ax + agu[i,j] * x[j]
        x[i] = (agu[i,n] - sum_ax) / agu[i,i] 

    print("the solution of the ystem:")
    print(x)


In [113]:
ref(agu)

row size is 3
[ 0.          0.         -1.33333333]
the solution of the ystem:
[ 0.66666667  7.         -1.33333333]


# Q2 You can explore in ANY of the following ways for Q2.
# Use ech form to solve system of equations (you cook up some equations) OR
# Do ech form matrix for general numbers, not just binary

## partial pivoting exchange rows
### partial pivoting is applied when the pivot is zero or very small in magnitude by interchaning the pivot row with a lower row

In [139]:
row = input("Enter the row size of the agumented matrix: ")
col = input("Enter the column size of the agumented matrix: ")
row = int(row)
col = int(col)

Enter the row size of the agumented matrix: 4
Enter the column size of the agumented matrix: 5


In [140]:
agu2 = np.zeros((row,col),float)
for i in range(row):
    for j in range(col):
        agu2[i][j] = input("Enter a[{0}][{1}]:".format(i,j))

Enter a[0][0]:0
Enter a[0][1]:1
Enter a[0][2]:2
Enter a[0][3]:3
Enter a[0][4]:-0.2
Enter a[1][0]:0
Enter a[1][1]:1
Enter a[1][2]:4
Enter a[1][3]:12
Enter a[1][4]:0.8
Enter a[2][0]:1
Enter a[2][1]:1
Enter a[2][2]:1
Enter a[2][3]:1
Enter a[2][4]:1.5
Enter a[3][0]:1
Enter a[3][1]:2
Enter a[3][2]:4
Enter a[3][3]:8
Enter a[3][4]:1.2


In [141]:
agu2

array([[ 0. ,  1. ,  2. ,  3. , -0.2],
       [ 0. ,  1. ,  4. , 12. ,  0.8],
       [ 1. ,  1. ,  1. ,  1. ,  1.5],
       [ 1. ,  2. ,  4. ,  8. ,  1.2]])

In [142]:
def ref_pp(agu):
    # able to handle agumented matrix A
    # Elimination

    n = len(agu)  # same as how many rows

    print("row size is", n)

    for k in range(n - 1):

        #if np.fabs(agu[k, k]) == 0:  # pivot is zero so we check row below to see if can swap check zero only
        #include the very small numbers that approach 0, 
        #safer as computer aproximate so if num is very small but not zero it wont make this estimate error
        if np.fabs(agu[k, k]) < 1.0e-20: 
            for i in range(k + 1, n):
                if np.fabs(agu[i, k]) > np.fabs(agu[k, k]):
                    agu[[i, k], :] = agu[[k, i], :]  # exchange the row
                    break  # once meet the first requirement and swap break and continue elimination of the columns to get the pivot

        for i in range(k + 1, n):
            if agu[i, k] == 0:
                continue
            factor = agu[k, k] / agu[i, k]
            for j in range(k, n + 1):
                agu[i, j] = agu[k, j] - agu[i, j] * factor
            # b[i] = b[k] - b[i] * factor # agumented column or the b
    print(agu)

    # back substitution part
    x = np.zeros(n,float)
    x[n-1] = agu[n-1,n] / agu[n-1,n-1] 

    # n-2 is the row just before last one, -1 as we want to stop after doing index 0 due to range,-1 to go backward
    for i in range(n - 2, -1, -1):
        sum_ax = 0
        for j in range(i + 1, n):
            sum_ax = sum_ax + agu[i, j] * x[j]
        x[i] = (agu[i, n] - sum_ax) / agu[i, i]

    print("the solution of the system:")
    print(x)

In [143]:
ref_pp(agu2)

row size is 4
[[ 1.   1.   1.   1.   1.5]
 [ 0.   1.   4.  12.   0.8]
 [ 0.   0.   2.   9.   1. ]
 [ 0.   0.   0.  -1.  -1.2]]
the solution of the system:
[-0.8  6.  -4.9  1.2]
